-- ============================================================
-- Object Name : AEROSPACE_PARTS_TARGET
-- Purpose     : ALTER TABLE - add new BRD columns SUPPLIER_RATING
--               and PIPELINE_RUN_WATERMARK; rename STATUS and
--               LOAD_TIMESTAMP columns per BRD/STTM specification
-- Author      : SUCHARITHAS
-- Generated   : 2026-09-24
-- ============================================================
BEGIN
    ALTER TABLE AEROSPACE_PARTS_TARGET ADD COLUMN IF NOT EXISTS SUPPLIER_RATING VARCHAR(100);
    ALTER TABLE AEROSPACE_PARTS_TARGET ADD COLUMN IF NOT EXISTS PIPELINE_RUN_WATERMARK TIMESTAMP_NTZ;
    BEGIN
        ALTER TABLE AEROSPACE_PARTS_TARGET RENAME COLUMN RECORD_STATUS TO STATUS;
        EXCEPTION WHEN OTHER THEN NULL;
    END;
    BEGIN
        ALTER TABLE AEROSPACE_PARTS_TARGET RENAME COLUMN ETL_LOAD_TIMESTAMP TO LOAD_TIMESTAMP;
        EXCEPTION WHEN OTHER THEN NULL;
    END;
END;