/*==============================================================
 File Name        : IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET.sql
 Object Name      : AEROSPACE_PARTS_TARGET
 Project          : SCRUM-135
 Purpose          : Target table DDL — Aerospace Parts Inventory pipeline
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-09-25
 Work Item        : SCRUM-135
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-09-25  AI Skill        ADAPT delta: +INVENTORY_HEALTH_STATUS column
==============================================================*/
CREATE OR ALTER TABLE IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET (
    PART_NUMBER              VARCHAR(100)    NOT NULL,
    MANUFACTURER             VARCHAR(300)    NOT NULL,
    WEIGHT_KG                NUMBER(12,4),
    CERTIFICATION_STATUS     VARCHAR(50),
    LEAD_TIME_DAYS           NUMBER(10),
    PART_NAME                VARCHAR(500),
    UNIT_PRICE_USD           NUMBER(18,2),
    CATEGORY                 VARCHAR(200),
    SUPPLIER_ID              VARCHAR(100),
    UPDATED_AT               TIMESTAMP_NTZ   NOT NULL,
    RISK_SCORE               VARCHAR(20)     NOT NULL,
    LOAD_TIMESTAMP           TIMESTAMP_NTZ   NOT NULL,
    PART_STATUS              VARCHAR(20)     DEFAULT 'Active',
    INVENTORY_HEALTH_STATUS  VARCHAR(50)                        -- [DELTA ADD] New column per BRD FR-009: inventory health & operational readiness monitoring
);