/*==============================================================
 File Name        : IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE_TASK.sql
 Object Name      : AEROSPACE_PARTS_INVENTORY_PIPELINE_TASK
 Project          : SCRUM-134
 Purpose          : Scheduled task — Daily at 05:00 UTC, triggers AEROSPACE_PARTS_INVENTORY_PIPELINE
 Generated By     : AI Skill - SDLC
 Generated Date   : 2026-09-25
 Work Item        : SCRUM-134
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-09-25  AI Skill        ADAPT: RECREATE scheduled task for AEROSPACE_PARTS_INVENTORY_PIPELINE
==============================================================*/
CREATE OR REPLACE TASK IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE_TASK
  WAREHOUSE = SNOWFLAKE_LEARNING_WH
  SCHEDULE = 'USING CRON 0 5 * * * UTC'
AS CALL IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE('INCREMENTAL');