/*==============================================================
 File Name        : IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE.sql
 Object Name      : AEROSPACE_PARTS_INVENTORY_PIPELINE
 Project          : SCRUM-135
 Purpose          : Incremental SCD Type 1 pipeline from AEROSPACE_PARTS_SOURCE
                    to AEROSPACE_PARTS_TARGET with RISK_SCORE derivation,
                    INVENTORY_HEALTH_STATUS derivation, soft delete,
                    and ETL_RECONCILIATION_LOG
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-09-25
 Work Item        : SCRUM-135
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-09-25  AI Skill        ADAPT delta: +EXECUTION_DURATION_SECONDS to ETL_RECONCILIATION_LOG
 2026-09-25  AI Skill        ADAPT delta: MANUFACTURER UPPER->INITCAP, RISK_SCORE thresholds >90 and <=70, +INVENTORY_HEALTH_STATUS
==============================================================*/
-- [DELTA REFERENCE] Adapted from: IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE
CREATE OR REPLACE PROCEDURE IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE(P_MODE VARCHAR DEFAULT 'INCREMENTAL')
RETURNS VARCHAR
LANGUAGE SQL
AS $$
DECLARE
    v_last_ts                 TIMESTAMP_NTZ;
    v_pipeline_start          TIMESTAMP_NTZ;
    v_load_mode               VARCHAR        DEFAULT 'INCREMENTAL';
    v_source_count            NUMBER         DEFAULT 0;
    v_target_count            NUMBER         DEFAULT 0;
    v_inserted_count          NUMBER         DEFAULT 0;
    v_updated_count           NUMBER         DEFAULT 0;
    v_decommissioned_count    NUMBER         DEFAULT 0;
    v_matched_count           NUMBER         DEFAULT 0;
    v_execution_duration      NUMBER         DEFAULT 0;
BEGIN

    v_pipeline_start := CURRENT_TIMESTAMP();

    -- Watermark Resolution
    IF (P_MODE = 'FULL') THEN
        v_last_ts   := '1900-01-01'::TIMESTAMP_NTZ;
        v_load_mode := 'FULL';
    ELSE
        SELECT COALESCE(MAX(RUN_TIMESTAMP), '1900-01-01'::TIMESTAMP_NTZ)
          INTO :v_last_ts
          FROM IDEA_2_DB.PUBLIC.ETL_RECONCILIATION_LOG
         WHERE PIPELINE_NAME = 'AEROSPACE_PARTS_INVENTORY_PIPELINE'
           AND STATUS = 'COMPLETED';
        v_load_mode := 'INCREMENTAL';
    END IF;

    -- Stage: Deduplication and Transformations
    CREATE OR REPLACE TEMPORARY TABLE AEROSPACE_PARTS_STAGE AS
    SELECT
        PART_NUMBER,
        INITCAP(MANUFACTURER)                                                      AS MANUFACTURER,           -- [DELTA MODIFY] MANUFACTURER: UPPER -> INITCAP (CamelCase per BRD AC-007, RULE-005)
        IFF(WEIGHT_KG <= 0, -1, WEIGHT_KG)                                        AS WEIGHT_KG,
        CERTIFICATION_STATUS,
        LEAD_TIME_DAYS,
        PART_NAME,
        ROUND(UNIT_PRICE_USD, 2)                                                   AS UNIT_PRICE_USD,
        CATEGORY,
        SUPPLIER_ID,
        UPDATED_AT,
        CASE
            WHEN CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 60  THEN 'High Risk'
            WHEN CERTIFICATION_STATUS = 'Pending' OR  LEAD_TIME_DAYS > 90  THEN 'Medium Risk'              -- [DELTA MODIFY] RISK_SCORE: Medium Risk threshold >100 -> >90 per BRD RULE-008
            WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 70 THEN 'Low Risk'    -- [DELTA MODIFY] RISK_SCORE: Low Risk threshold <=60 -> <=70 per BRD RULE-009
            ELSE 'Medium Risk'
        END                                                                        AS RISK_SCORE,
        CASE
            WHEN CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 60  THEN 'At Risk'                 -- [DELTA ADD] INVENTORY_HEALTH_STATUS: new derived column per BRD FR-009, BR-008
            WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 70 THEN 'Healthy'
            WHEN LEAD_TIME_DAYS > 90                                               THEN 'Monitor'
            ELSE 'Monitor'
        END                                                                        AS INVENTORY_HEALTH_STATUS,
        CURRENT_TIMESTAMP()                                                        AS LOAD_TIMESTAMP
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS RN
          FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_SOURCE
         WHERE UPDATED_AT > :v_last_ts
    ) deduped
    WHERE RN = 1;

    -- Row Counts
    SELECT COUNT(*) INTO :v_source_count  FROM AEROSPACE_PARTS_STAGE;
    SELECT COUNT(*) INTO :v_target_count  FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET;
    SELECT COUNT(*) INTO :v_inserted_count
      FROM AEROSPACE_PARTS_STAGE stg
     WHERE NOT EXISTS (SELECT 1 FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET tgt
                        WHERE tgt.PART_NUMBER = stg.PART_NUMBER);
    SELECT COUNT(*) INTO :v_updated_count
      FROM AEROSPACE_PARTS_STAGE stg
     WHERE EXISTS (SELECT 1 FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET tgt
                    WHERE tgt.PART_NUMBER = stg.PART_NUMBER);
    v_matched_count := :v_source_count;

    -- SCD Type 1 MERGE
    MERGE INTO IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET tgt
    USING AEROSPACE_PARTS_STAGE src
       ON tgt.PART_NUMBER = src.PART_NUMBER
    WHEN MATCHED THEN UPDATE SET
        tgt.MANUFACTURER             = src.MANUFACTURER,
        tgt.WEIGHT_KG                = src.WEIGHT_KG,
        tgt.CERTIFICATION_STATUS     = src.CERTIFICATION_STATUS,
        tgt.LEAD_TIME_DAYS           = src.LEAD_TIME_DAYS,
        tgt.PART_NAME                = src.PART_NAME,
        tgt.UNIT_PRICE_USD           = src.UNIT_PRICE_USD,
        tgt.CATEGORY                 = src.CATEGORY,
        tgt.SUPPLIER_ID              = src.SUPPLIER_ID,
        tgt.UPDATED_AT               = src.UPDATED_AT,
        tgt.RISK_SCORE               = src.RISK_SCORE,
        tgt.INVENTORY_HEALTH_STATUS  = src.INVENTORY_HEALTH_STATUS,  -- [DELTA ADD] INVENTORY_HEALTH_STATUS included in MERGE UPDATE SET
        tgt.LOAD_TIMESTAMP           = src.LOAD_TIMESTAMP,
        tgt.PART_STATUS              = 'Active'
    WHEN NOT MATCHED THEN INSERT (
        PART_NUMBER, MANUFACTURER, WEIGHT_KG, CERTIFICATION_STATUS,
        LEAD_TIME_DAYS, PART_NAME, UNIT_PRICE_USD, CATEGORY,
        SUPPLIER_ID, UPDATED_AT, RISK_SCORE, INVENTORY_HEALTH_STATUS, LOAD_TIMESTAMP, PART_STATUS
    ) VALUES (                                                                     -- [DELTA ADD] INVENTORY_HEALTH_STATUS included in MERGE INSERT
        src.PART_NUMBER, src.MANUFACTURER, src.WEIGHT_KG, src.CERTIFICATION_STATUS,
        src.LEAD_TIME_DAYS, src.PART_NAME, src.UNIT_PRICE_USD, src.CATEGORY,
        src.SUPPLIER_ID, src.UPDATED_AT, src.RISK_SCORE, src.INVENTORY_HEALTH_STATUS, src.LOAD_TIMESTAMP, 'Active'
    );

    -- Soft Delete: Mark decommissioned records
    UPDATE IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET
       SET PART_STATUS              = 'Decommissioned',
           INVENTORY_HEALTH_STATUS  = 'Decommissioned'                             -- [DELTA ADD] Sync INVENTORY_HEALTH_STATUS = Decommissioned on soft delete per BRD RULE-004
     WHERE PART_STATUS <> 'Decommissioned'
       AND PART_NUMBER NOT IN (
           SELECT PART_NUMBER FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_SOURCE
       );
    v_decommissioned_count := SQLROWCOUNT;

    v_execution_duration := DATEDIFF('second', :v_pipeline_start, CURRENT_TIMESTAMP());

    -- Reconciliation Log
    INSERT INTO IDEA_2_DB.PUBLIC.ETL_RECONCILIATION_LOG (
        RECON_ID, PIPELINE_NAME, RUN_TIMESTAMP,
        SOURCE_COUNT, TARGET_COUNT, MATCHED_COUNT,
        INSERTED_COUNT, UPDATED_COUNT, DECOMMISSIONED_COUNT,
        LOAD_MODE, STATUS, NOTES, EXECUTION_DURATION_SECONDS
    ) VALUES (
        UUID_STRING(), 'AEROSPACE_PARTS_INVENTORY_PIPELINE', CURRENT_TIMESTAMP(),
        :v_source_count, :v_target_count, :v_matched_count,
        :v_inserted_count, :v_updated_count, :v_decommissioned_count,
        :v_load_mode, 'COMPLETED',
        'Pipeline completed successfully. Mode: ' || :v_load_mode,
        :v_execution_duration
    );

    RETURN 'SUCCESS: Mode=' || :v_load_mode
        || ' | Source='         || :v_source_count::VARCHAR
        || ' | Inserted='       || :v_inserted_count::VARCHAR
        || ' | Updated='        || :v_updated_count::VARCHAR
        || ' | Decommissioned=' || :v_decommissioned_count::VARCHAR
        || ' | Duration(s)='    || :v_execution_duration::VARCHAR;

EXCEPTION WHEN OTHER THEN
    INSERT INTO IDEA_2_DB.PUBLIC.ETL_RECONCILIATION_LOG (
        RECON_ID, PIPELINE_NAME, RUN_TIMESTAMP,
        SOURCE_COUNT, TARGET_COUNT, MATCHED_COUNT,
        INSERTED_COUNT, UPDATED_COUNT, DECOMMISSIONED_COUNT,
        LOAD_MODE, STATUS, NOTES, EXECUTION_DURATION_SECONDS
    ) VALUES (
        UUID_STRING(), 'AEROSPACE_PARTS_INVENTORY_PIPELINE', CURRENT_TIMESTAMP(),
        :v_source_count, :v_target_count, 0, 0, 0, 0,
        :v_load_mode, 'FAILED',
        'Pipeline failed: ' || SQLERRM,
        DATEDIFF('second', :v_pipeline_start, CURRENT_TIMESTAMP())
    );
    RETURN 'ERROR: ' || SQLERRM;
END;
$$;