/*==============================================================
 File Name        : IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_TASK.sql
 Object Name      : AEROSPACE_PARTS_INVENTORY_TASK
 Project          : SCRUM-135
 Purpose          : Scheduled task — daily at 03:00 UTC triggering AEROSPACE_PARTS_INVENTORY_PIPELINE
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-09-25
 Work Item        : SCRUM-135
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-09-25  AI Skill        ADAPT: Recreated task with updated pipeline reference
==============================================================*/
CREATE OR REPLACE TASK IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_TASK
  WAREHOUSE = SNOWFLAKE_LEARNING_WH
  SCHEDULE = 'USING CRON 0 3 * * * UTC'
AS CALL IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE('INCREMENTAL');